
site_name: Nuka AI Research Series
site_url: https://nuka-ai.github.io
docs_dir: docs

theme:
  name: material
  logo: assets/hero.png
  favicon: assets/hero.png
  palette:
    - scheme: slate
      primary: black
      accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

plugins:
  - search
  # This creates the nice preview cards for X/Twitter
  - social:
      cards_layout: theme/nuka-ai 

nav:
  - Home: index.md
  - Research Logs: 
    - Overview: posts/init.md
    - April 23 Disclosure: posts/2026-07-14-initial-disclosure.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nuka-AI
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/JDPSec
    - icon: fontawesome/solid/paper-plane
      link: mailto:Nuka.AI@proton.me
