site_name: Nuka AI Research Series
site_url: https://nuka-ai.github.io
docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: red

plugins:
  - search
  - blog:
      blog_dir: posts
      post_dir: posts

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nuka-AI
